### ISSUE TITLE
Serialization and Swift Package Manager

### ISSUE THREAD

**Issue by kristojorg** [roznet/fit-sdk-swift#2]
Hi there,

thanks for providing this repo! I've been doing some research into a library for parsing and serializing FIT files from swift. I'm curious if you've thought about including a similar script to convert the serialization example? Also, what do you think about providing this as a swift package? 

I'm currently looking at wrapping the C or C++ SDK in a Swift package, but your approach is also interesting to me, and if mine turns out to be too slow, I'll be using yours. Anyways, just wanted to get your thoughts on this before I get too far down the road.

Thanks a bunch!

**Comment by kristojorg** [comment]
So I have begun poking around at making this a Swift package, and I am running in to some errors. I'm not super experienced about this stuff, so I figure I'll put this here and see if you have any thoughts. My repository I've started doing this in is here: https://github.com/kristojorg/SwiftFit . I started with a clean repo for debugging purposes, but once I get this working I will make a PR back to your repo with it if you'd like.

I reorganized the code a bit since Swift packages cannot have mixed sources. Thus I made a `RZFitFileTypes` target containing the C SDK from your project, and a `RZFitFile` target containing the Swift code. I also moved the python conversion code to `/Python`. I wasn't sure what to do with the `.m` files like  `rzfit_convert_auto.m`, so for the time being they are in their own folder `Sources/Other`. 

I am getting an error when compiling `RZFitFileTypes`. It is saying that there are duplicate symbols in `fit_example.o` and `fit_product.o`. My guess is that something is wrong with how these are being included? I'm not sure. Do you have any thoughts here? 

Here is the full error from Xcode:

```
duplicate symbol '_device_file_mesgs' in:
    /Users/ksj/Library/Developer/Xcode/DerivedData/SwiftFIT-dmbzzqshrhzdwbajcxcaksiqomjr/Build/Intermediates.noindex/SwiftFIT.build/Debug-iphonesimulator/RZFitFileTypes.build/Objects-normal/x86_64/fit_example.o
    /Users/ksj/Library/Developer/Xcode/DerivedData/SwiftFIT-dmbzzqshrhzdwbajcxcaksiqomjr/Build/Intermediates.noindex/SwiftFIT.build/Debug-iphonesimulator/RZFitFileTypes.build/Objects-normal/x86_64/fit_product.o
duplicate symbol '_fit_mesg_defs' in:
    /Users/ksj/Library/Developer/Xcode/DerivedData/SwiftFIT-dmbzzqshrhzdwbajcxcaksiqomjr/Build/Intermediates.noindex/SwiftFIT.build/Debug-iphonesimulator/RZFitFileTypes.build/Objects-normal/x86_64/fit_example.o
    /Users/ksj/Library/Developer/Xcode/DerivedData/SwiftFIT-dmbzzqshrhzdwbajcxcaksiqomjr/Build/Intermediates.noindex/SwiftFIT.build/Debug-iphonesimulator/RZFitFileTypes.build/Objects-normal/x86_64/fit_product.o
duplicate symbol '_fit_file_defs' in:
    /Users/ksj/Library/Developer/Xcode/DerivedData/SwiftFIT-dmbzzqshrhzdwbajcxcaksiqomjr/Build/Intermediates.noindex/SwiftFIT.build/Debug-iphonesimulator/RZFitFileTypes.build/Objects-normal/x86_64/fit_example.o
    /Users/ksj/Library/Developer/Xcode/DerivedData/SwiftFIT-dmbzzqshrhzdwbajcxcaksiqomjr/Build/Intermediates.noindex/SwiftFIT.build/Debug-iphonesimulator/RZFitFileTypes.build/Objects-normal/x86_64/fit_product.o
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by roznet** [comment]
I'll take a look. But I had struggled a bit to configure it to compile and be usable in swift/objective on macOS and iOS, as my project are cross platform and have legacy of old languages.

**Comment by roznet** [comment]
I got it working, I renamed it as the package manager didn't seem to like the dash in the name

I'll probably push it back to this repo as well and make the name more consistent when I have Time to fix the dependencies, but for now you can find the package manager in 

https://github.com/roznet/FitFileParser

**Comment by roznet** [comment]
I changed this repo to be just example of using the package manager in https://github.com/roznet/FitFileParser

And I also update [ConnectStats](https://github.com/roznet/connectstats) to use the new package. 

Thanks a lot for the suggestion, I wasn't familiar with Swift Package Manager and it's actually very nice and convenient!

**Comment by kristojorg** [comment]
Wow this is super helpful! Thank you so much for the speedy help there : ). I'm going to investigate getting serialization to work in the new swift package repo. Cheers!

**Comment by roznet** [comment]
Yes, I have been thinking of doing serialisation for a while, but never got around to it. 

Maybe start a new issue on the new library for that? (Or should I do it?)

**Comment by kristojorg** [comment]
Just opened: https://github.com/roznet/FitFileParser/issues/2
